# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Book.destroy_all
User.destroy_all
Review.destroy_all

Book.reset_pk_sequence
User.reset_pk_sequence
Review.reset_pk_sequence
#####Book Seed##########################
book1= Book.create(title:"Can't Even: How millenials became the burnout generation" ,authors:"Anne Helen Petersen", publisher: "Houghton Mifflin Harcourt" , published_date: "September 22,2020" , description:"In this razor-sharp book of cultural criticism spun off from her viral BuzzFeed article, journalist and academic Anne Helen Petersen explores the forces that have left a much-maligned generation feeling disempowered and dispossessed, from the gig economy to the monetization of hobbies to the identity-bending influence of social media. With blistering prose and all-too vivid reporting, Petersen lays bare the burnout and despair of millennials, while also charting a path to a world where members of her generation can feel as if the boot has been removed from their necks." , image:"https://m.media-amazon.com/images/I/41LPS493-VL.jpg"  , main_category:"Social Sciences")
book2= Book.create(title:"Just Us:An American Conversation" ,authors:"Claudia Rankine", publisher:"GrayWolf Press" , published_date:"September 8,2020" , description:"The visionary writer of Citizen returns with Just Us, a lyric arrangement of poems, essays, and images asking how a historically divided nation might come together to dismantle white supremacy. In a far-ranging imagined conversation, a chorus of disparate voices engage in a call and response discussion, with each encounter rooted in a different corner of American life. In Citizen, Rankine redefined how we think about and understand race; in Just Us, she redefines how we might converse about race across divisions, making for a meditative, powerful rumination on the life-changing importance of hard conversations, even in the absence of answers." , image:"https://images-na.ssl-images-amazon.com/images/I/41a8wf+2C6L._SY344_BO1,204,203,200_.jpg", main_category:"Poetry")
book3= Book.create(title:"Red Pill" ,authors:"Hari Hunzru", publisher: "Knopf Publishing Group" , published_date:"September 1,2020" , description: "A master of weaving political life and postmodern anxiety into fiction, Kunzru, the acclaimed author of White Tears, returns to form with Red Pill, a dazzling novel about an American writer abroad who falls down the rabbit hole of alt-right message boards and government conspiracies. Rarely has our contemporary animus been so nakedly illuminated on the page, with Kunzru spinning a dizzying allegory from the puzzling, paranoid mind of a narrator set adrift in unreality." , image:"https://images-na.ssl-images-amazon.com/images/I/41THomic1dL._SX340_BO1,204,203,200_.jpg"  , main_category:"Genre Fiction")
book4= Book.create(title:"Pizza Girl" ,authors:"Jean Kyoung Frazier", publisher: "Penguin Random House", published_date:"June 9,2020" , description:"In Frazier’s explosive debut novel, our nameless narrator is eighteen, pregnant, and feeling adrift as she stumbles through her days as a Los Angeles pizza delivery driver, all the while grieving the death of her alcoholic father and avoiding the smothering ministrations of her loving mother and boyfriend. Everything changes when she delivers a peculiar order to a suburban housewife, who becomes the locus of a pyschosexual obsessesion with dangerous consequences. In just 193 wry, propulsive pages, Pizza Girl hurtles through the dark waters of obsession and addiction, as our dysfunctional Pizza Girl downs Miller Lites while studiously avoiding any semblance of forward motion. Yet at the same time, the novel bristles with biting wit and optimism, each page a feast of Cheeto-fingered heart, humor, and lyricism." , image:"https://images-na.ssl-images-amazon.com/images/I/51WesY0SdEL._SX329_BO1,204,203,200_.jpg" , main_category:"Humor")
book5= Book.create(title:"Must I go" ,authors:"Yiyun Li", publisher:"Penguin Random House" , published_date: "July 28,2020", description:"In Must I Go, Li captures a difficult woman nearing the end of her days. At age 88, after three husbands, five children, and seventeen grandchildren, Lilia Liska looks back on her uncompromising life from the numbing stasis of a nursing home, where she fills her hours annotating the newly published diaries of Roland Bouley, a deceased writer with whom she once had a fleeting affair. Though Lilia was merely a footnote in Roland’s life, she wars with his recollection of events, speculating about his two great loves while shading in the brutal details of her own long-buried personal history. She returns unendingly to the memory of her daughter Lucy, who took her own life at 27, and to the bottomless grief of losing a child to suicide. Li's greatest talent lies in her peerless experimentation with our language of human emotion—its insufficiencies, its dissatisfactions, its refusal to capture the depth and breadth of our feelings. Must I Go is another remarkable entry in Li’s decades-long tug-of-war with the English language, which, luckily for her devoted readers, shows no signs of abating anytime soon." , image:"https://images-na.ssl-images-amazon.com/images/I/41ZLF+VWH8L._SX327_BO1,204,203,200_.jpg"  , main_category:"Genre Fiction")
book6= Book.create(title:"Boys of Albama" ,authors:"Genevieve Hudson", publisher:"Liverright Publishing Corporation" , published_date:"May 19,2020" , description:"When Max relocates from the cool reserve of Germany to the sweaty American south, he brings along a host of supernatural secrets. But as he’s embraced by his new football teammates, his red dirt Alabama surroundings, steeped in the past and unwaveringly Christian, make him question everything—from his faith and sexuality to the very nature of his desire. Hudson’s debut, written in undeniable, visceral prose, is downright ravishing." , image: "https://images-na.ssl-images-amazon.com/images/I/51guSr++5vL._SY344_BO1,204,203,200_.jpg" , main_category:"Literature and Fiction")
book7= Book.create(title:"They Wish They Were Us" ,authors:"Jessica Goodman", publisher:"Penguin Random House" , published_date:"August 4,2020" , description:"Entree into the ruling inner circle of Long Island’s elite Gold Coast Prep gets served up deliciously in this debut YA novel from Cosmopolitan senior editor Jessica Goodman. The chilling murder mystery is an irresistible hook, but it’s the careful building of each character’s fraught, internal conflicts that really digs in, elevating the work from a high society whodunit to a knowing mission to not just uncover one’s own identity, but to build it." , image:"https://images-na.ssl-images-amazon.com/images/I/51g2fhhwe0L._SX329_BO1,204,203,200_.jpg", main_category:"Literature and Fiction")
book8= Book.create(title:"Hollywood Park" ,authors:"Mikel Jollett", publisher:"Celadon Books" , published_date:"May 26,2020" , description:"Not many rock memoirs begin on the grounds of an infamous American cult, but that’s just one of the things about the Airborne Toxic Event frontman’s personal tome that separates it from the droves. Cinematic in its recounting of his family’s exit from the Synanon commune in California, Jollet’s subsequent unraveling of the abuses that shaped his stolen childhood is piercing. His pain feels at once unknowable and universal, and his rhapsodic writing makes Hollywood Park impossible to put down." , image:"https://images-na.ssl-images-amazon.com/images/I/41pA8mIXOZL._SX327_BO1,204,203,200_.jpg"  , main_category:"Arts and Literature")
book9= Book.create(title:"A Children's Bible" ,authors:"Lydia Millet", publisher:"Norton and Company" , published_date:"May 12,2020" , description:"From one of our finest writers of climate fiction comes a harrowing novel of environmental dystopia, wherein a group of families summering together at a vacation home are stranded by the climate apocalypse. When the storm to end all storms descends on their remote rental, the teenagers conclude that their debauched parents are unfit to care for them and strike out on their own, only to encounter all manner of biblical calamities in the wilderness. In an age when the dispossessed young generation blames the pillaging older generation for their ravaged environmental inheritance, Millet’s work has never been more timely." , image:"https://images-na.ssl-images-amazon.com/images/I/5122OrJIlPL._SX329_BO1,204,203,200_.jpg" , main_category:"Genre Fiction")
book10= Book.create(title:"How Much of These Hills Is Gold" ,authors:"Pam Zhang", publisher:"Penguin Random House" , published_date:"April 7,2020" , description:"In this glittering debut, Zhang sets the scene in the dying days of the gold rush, where two orphaned children of Chinese immigrants roam the ravaged American west in search of a new home, only to meet hostility everywhere they go—not just from the unforgiving landscape, but from the racist and inhospitable locals. As these siblings form their nascent identities under the colossal weight of their loss, they reimagine their own history and their own heritage. This novel is at once a thrilling adventure, a tender coming-of-age story, an excavation of the corrosive mythmaking surrounding the American west, and the arrival of a major literary talent.", image:"https://images-na.ssl-images-amazon.com/images/I/514nj5qWToL._SX329_BO1,204,203,200_.jpg", main_category:"Genre Fiction")
book11= Book.create(title:"Drifts: A novel" ,authors:"Kate Zambreno", publisher:"Penguin Random House" , published_date:"May 19,2020" , description:"One of our most formally ambitious writers returns with a sublime new fiction about a woman struggling to finish her overdue novel, as she becomes increasingly obsessed with the challenge of writing in the present tense and capturing the slippery nature of time. Her creative blockage leads her to take up lengthy correspondences with her friends, as well as lose herself in the works of the dead greats, whose creative crusades shed light onto her own. Give yourself over to the undulant music of this bold novel, and let yourself be buffeted along restless journey of the narrator’s creative awakening." , image:"https://images-na.ssl-images-amazon.com/images/I/41ENbFoytoL._SX329_BO1,204,203,200_.jpg", main_category:"Genre Fiction")
book12= Book.create(title:"If I had your face" ,authors:"Frances Cha", publisher:"Penguin Random House" , published_date:"April 21,2020" , description:"In Seoul, South Korea, four young women living in the same apartment complex stumble through a K-pop-soaked cultural miasma of misogyny, consumerism, and unattainable beauty standards. Come for the tender portrait of female friendship in all its tears and triumphs, but stay for the sharp dissection of contemporary life for women, mired as it is in demeaning cultural norms, male primacy, and dwindling economic opportunities." , image:"https://images-na.ssl-images-amazon.com/images/I/51U+LIEN1TL._SX327_BO1,204,203,200_.jpg", main_category:"Genre Fiction")
book13= Book.create(title:"Sansei and Sensibility" ,authors:"Karen Tei Yamashita", publisher:"Coffee House Press" , published_date:"May 5,2020" , description:"In these daring and delightful stories, Yamashita remixes Jane Austen’s classic novels with the Japanese American immigrant experience, as seen through the lives of SoCal families in the sixties and seventies. With Mr. Darcy captaining the football team and public school bake sales replacing Austen’s mannered countryside balls, Yamashita questions the wisdom of generations and the meaning of inheritance in these bold stories that transcend race, place, and time." , image:"https://images-na.ssl-images-amazon.com/images/I/51+VNp-BT5L._SX331_BO1,204,203,200_.jpg", main_category:"Short Sotries and Anthologies")
book14= Book.create(title:"GodShot" ,authors:"Chelsea Bieker", publisher:"Publishers Group West", published_date:"March 31,2020" , description:"Religious zealotry meets environmental meltdown in Godshot, Bieker’s spectacular novel about a teenager abandoned to a local cult upon her troubled mother’s exile from the community. In drought-stricken Peaches, California, a charismatic cult pastor promises to bring rain―so long as his brainwashed followers complete the “assignments” he asks of them. When fourteen-year-old Lacey learns the truth of this community, built as it is on patriarchal norms and sexual abuse, she skips town on a quest to retrieve her mother. What follows is a gritty, gripping tale of girlhood, spirituality, and how salvation comes from the unlikeliest of places.", image:"https://images-na.ssl-images-amazon.com/images/I/618tF3rKitL._SX332_BO1,204,203,200_.jpg", main_category:"Genre Fiction")
book15= Book.create(title:"Exciting Times" ,authors:"Naoise Dolan", publisher:"Harper Collins" , published_date:"June 2,2020" , description:"In this wry, stylish debut, Dolan sets her sights on Ava, an Irish expat teaching English to the wealthy children of Hong Kong. Ava soon becomes romantically entangled with Julian, a rich banker who can’t commit, as well as with Edith, a lawyer who inspires both envy and desire. In this witty satire of the haves and have nots, Dolan explores tender, insightful truths about the vagaries of modern love.", image:"https://images-na.ssl-images-amazon.com/images/I/41rTQOSb4sL._SX327_BO1,204,203,200_.jpg", main_category:"Literature and Fiction")
book16= Book.create(title:"Memorial Drive" ,authors:"Natasha Tretheway", publisher:"Harper Collins", published_date:"July 28,2020" , description:"For Natasha Trethewey, the end is very much the beginning, for both her startling new memoir and, as we learn across its pages, the second iteration of herself. The work opens in the immediate aftermath of her mother’s murder—committed by Trethewey’s former stepfather when the author was just 19—before confronting the years preceding the event, which she admits she’d long treated with “willed amnesia buried deep in me like a root.” Propelled by the Pulitzer Prize-winning U.S. poet laureate’s remarkable command of language, it’s a story that burrows deep in your emotional center. And often, as the nonlinear retelling dances between years, dreams, and hazy memories, the work enraptures like a thriller, unraveling as it races against the inevitable.", image:"https://images-na.ssl-images-amazon.com/images/I/41Frzr9I1LL._SX329_BO1,204,203,200_.jpg", main_category:"Americas")
book17= Book.create(title:"Last Couple Standing", authors:"Matthew Norman", publisher:"Penguin Random House" , published_date:"March 17,2020", description:"When Jessica and Mitch Butler were first married, they were one of four best friend couples—aka The Core Four—from college who’d all paired up. 15 years later, they’re the only set still together. Stuck in a rut but desperate to avoid divorce, Jessica suggests they try an “evolved” marriage, where one-night stands and random hook-ups with strangers are pitched as potential ways to light a spark back home. It’s an idea that spars with their relationship as much as reality, but Norman’s funny and feeling writing makes for an irresistible read.", image:"https://images-na.ssl-images-amazon.com/images/I/41VSVxPCsIL._SX329_BO1,204,203,200_.jpg", main_category:"Genre Fiction")
book18= Book.create(title:"The Jetsetters",authors:"Amanda Eyre",publisher:"Penguin Random House", published_date:"March 3,2020", description:"In Eyre Ward’s (How to Be Lost, The Same Sky) The Jetsetters, everyone is, to put it mildly, a colossal wreck. Lucky for us, they each—all three Perkins children, plus their widowed matriarch Charlotte—also get a say. Told in alternating chapters, Eyre Ward’s genuine, hilarious writing rotates between each character’s perspective over the course of a week-long European cruise, producing a story of deep-seated familial discord and desire that falls apart as spectacularly as it wills itself back together. If you’re in the market for an escape, look no further.", image:"https://images-na.ssl-images-amazon.com/images/I/51tmjpnWN7L._SX329_BO1,204,203,200_.jpg", main_category:"Genre Fiction")
book19= Book.create(title:"Golden Gates:Fighting for Housing in America",authors:"Conor Doughtery",publisher:"Penguin Random House", published_date:"February 18,2020", description:"What could be a dry narrative of the housing crisis is utterly gripping in Dougherty’s hands, told as it is through the lens of individuals in San Francisco struggling with rising rents, housing scarcity, and poverty. Through zippy prose and deep reporting, Dougherty, a former housing reporter for The Wall Street Journal, explains why housing has become unaffordable and how we can solve the problem--that is, if we want to.", image:"https://images-na.ssl-images-amazon.com/images/I/31PSA6IG00L._SX327_BO1,204,203,200_.jpg", main_category:"Americas")
book20= Book.create(title:"American Poison: How Racial Hostility Destroyed Our Promise",authors:"Eduardo Porter",publisher:"Penguin Random House", published_date:"January 21,2020", description:"In this fascinating book, Porter sees the matrix of race in America. Weaving together social science research and historical context, he dissects how racism infects every stratum of American society, from unions to public education to immigration policy. Porter, a New York Times economics reporter who has covered the intersection of race and economics around the world, is uniquely conversant and globally-minded on these issues.", image:"https://m.media-amazon.com/images/I/41IcbOpmDQL.jpg", main_category:"Politics and Social Sciences")

########User Seed########################
user1= User.create(username:"BettyBoop", profile_description:"Conquering the world,one book at a time!")
user2= User.create(username:"Daisy123", profile_description:"Digital content creator and coffee officiando.")
user3= User.create(username:"Abelt", profile_description:"Mechanical Engineer-discovering business and engineering books.")
user4= User.create(username:"Mesi", profile_description:"I love an evening with a nice glass of wine and a good book.")
user5= User.create(username:"Tesla", profile_description:"Self proclaimed book nerd, so I love books, books and books!")
user6= User.create(username:"Virginia", profile_description:"One has to read about the past, in order to discover the future.")
user7= User.create(username:"Whoopi", profile_description:"Future UX/UI designer. Love nothing more than to learn everything about design.")
user8= User.create(username:"Morty", profile_description:"Physics and the dimensional planes! Ask me about anything string theory related")
user9= User.create(username:"MeskelFlower", profile_description:"I come from a fashion background but my favorite series are Dummy's guides to anything lol.")
user10= User.create(username:"Victor", profile_description:"I am just a passionate reader!!!!")

##########Review Seed#####################
review1= Review.create(comment:"Was an interesting book.", ratings:3, user_id:user1.id, book_id:book20.id)
review2= Review.create(comment:"There is something to say about Racial hostility and this book does a great job of covering a layer of it.", ratings:4, user_id:user10.id, book_id:book20.id)
review3= Review.create(comment:"A word play on the original sense and sensibilities classic. The title alone says it all!", ratings:4, user_id:user2.id, book_id:book13.id)
review4= Review.create(comment:"I just simply disagree with all that was said.", ratings:1, user_id:user1.id, book_id:book1.id)
review5= Review.create(comment:"This books touches on the leading issue in America. Especially post covid!", ratings:3, user_id:user2.id, book_id:book19.id)
review6= Review.create(comment:"I am American, and I have a house. Was it necessary to write a whole book about it. The answer is no.", ratings:1, user_id:user5.id, book_id:book19.id)
review7= Review.create(comment:"Funny book. I wonder what someone would do if they had my face? A great read.", ratings:5, user_id:user9.id, book_id:book12.id)
review8= Review.create(comment:"Nothing like the book title. Delves into issues of about the environment, nicely wrapped in a fiction.", ratings:4, user_id:user7.id, book_id:book9.id)
review9= Review.create(comment:"Very interesting novel, that is warped into love and mystery.", ratings:3, user_id:user9.id, book_id:book17.id)
review10= Review.create(comment:"Absolutely hated this book. Would not recommend!!!", ratings:1, user_id:user8.id, book_id:book8.id)
review11= Review.create(comment:"Was it a good read yes! But was it worth recommending, I really don't know.", ratings:3, user_id:user4.id, book_id:book14.id)
review12= Review.create(comment:"I wish I was them lol. Definitely worth the read", ratings:4, user_id:user7.id, book_id:book7.id)

# review13= Review.create(comment:, ratings:, user_id:, book_id:)

puts "I have seeded!"